/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SneakyCodeGUI;

import Desencriptar.DSustitucion;
import Desencriptar.DTransposicion;
import Encriptar.ESustitucion;
import Encriptar.ETransposicion;
import Tools.Sneaky;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author The Worst One
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    private Sherlock sherlock = new Sherlock();
    private ETransposicion cryptTrans;
    private DTransposicion decryptTrans;
    private ESustitucion cryptSust;
    private DSustitucion decryptSust;
    
    public home() {
        initComponents();
        this.getContentPane().setBackground(new Color(0, 153, 153));
        setLocationRelativeTo(null);
        cryptTrans = new ETransposicion();
        decryptTrans = new DTransposicion();
        cryptSust = new ESustitucion();
        decryptSust = new DSustitucion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Cambiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Entrada = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        Metodo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Descifrar = new javax.swing.JButton();
        Cifrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Clave = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Abrir = new javax.swing.JMenu();
        Cryptanalysis = new javax.swing.JMenu();
        Sherlock = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Esta es su salida:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salida.setEditable(false);
        Salida.setColumns(20);
        Salida.setRows(5);
        jScrollPane1.setViewportView(Salida);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 610, 210));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Texto de Salida:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 191, 21));

        Refresh.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 70, 20));

        Save.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Save.setText("Guardar");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 110, 30));

        Cambiar.setFont(new java.awt.Font("Verdana", 0, 8)); // NOI18N
        Cambiar.setText("Switch");
        Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarActionPerformed(evt);
            }
        });
        jPanel1.add(Cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 70, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 665, 300));

        jPanel2.setBackground(new java.awt.Color(161, 140, 225));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Especifique el proceso: ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 11))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Entrada.setColumns(20);
        Entrada.setRows(5);
        jScrollPane2.setViewportView(Entrada);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, 160));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Metodo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Metodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sustitución", "Transposición" }));
        jPanel3.add(Metodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Ingrese la clave: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 21));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, 10));

        Descifrar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Descifrar.setText("Descifrar");
        Descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescifrarActionPerformed(evt);
            }
        });
        jPanel3.add(Descifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, 30));

        Cifrar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Cifrar.setText("Cifrar");
        Cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CifrarActionPerformed(evt);
            }
        });
        jPanel3.add(Cifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Seleccione el método: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 21));

        Clave.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Clave.setModel(new javax.swing.SpinnerNumberModel(1, 1, 27, 1));
        jPanel3.add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 80, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, 170));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Texto de Entrada:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 191, 21));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 665, 200));

        Abrir.setText("Abrir");
        Abrir.setMaximumSize(new java.awt.Dimension(100, 32767));
        Abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbrirMouseClicked(evt);
            }
        });
        jMenuBar1.add(Abrir);

        Cryptanalysis.setText("Cryptanalysis");
        Cryptanalysis.setMaximumSize(new java.awt.Dimension(100, 32767));
        Cryptanalysis.setPreferredSize(new java.awt.Dimension(48, 19));
        Cryptanalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CryptanalysisMouseClicked(evt);
            }
        });
        jMenuBar1.add(Cryptanalysis);

        Sherlock.setText("Sherlock");
        Sherlock.setMaximumSize(new java.awt.Dimension(100, 32767));
        Sherlock.setPreferredSize(new java.awt.Dimension(48, 19));
        Sherlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SherlockMouseClicked(evt);
            }
        });
        jMenuBar1.add(Sherlock);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        Entrada.setText("");
        Salida.setText("");
    }//GEN-LAST:event_RefreshActionPerformed

    private void AbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbrirMouseClicked
        String aux="";   
        String texto="";
        try
        {
         JFileChooser file=new JFileChooser();
         file.showOpenDialog(this);

         File abre=file.getSelectedFile();

         if(abre!=null)
         {     
            FileReader archivos=new FileReader(abre);
            BufferedReader lee=new BufferedReader(archivos);
            while((aux=lee.readLine())!=null)
            {
               texto+= aux+ "\n";
            }
               lee.close();
          }    
         }
         catch(IOException ex)
         {
           JOptionPane.showMessageDialog(null,ex+"" +
                 "\nNo se ha encontrado el archivo",
                       "",JOptionPane.WARNING_MESSAGE);
          }
        Entrada.setText(texto);
    }//GEN-LAST:event_AbrirMouseClicked

    private void CifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CifrarActionPerformed
        if (Metodo.getSelectedIndex()==1)
        {
            Salida.setText(cryptTrans.encriptar((int) Clave.getValue(), Entrada.getText()));
        }else
        {
            Salida.setText(cryptSust.encriptar((int)Clave.getValue(), Entrada.getText()));
        }
    }//GEN-LAST:event_CifrarActionPerformed

    private void DescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescifrarActionPerformed
        if (Metodo.getSelectedIndex()==1)
        {
            Salida.setText(decryptTrans.desencriptar((int) Clave.getValue(), Entrada.getText()));
        }else
        {
            Salida.setText(decryptSust.desencriptar((int) Clave.getValue(),Entrada.getText()));
        }
    }//GEN-LAST:event_DescifrarActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        try
        {
         String nombre="";
         JFileChooser file=new JFileChooser();
         file.showSaveDialog(this);
         File guarda =file.getSelectedFile();

         if(guarda !=null)
         {
           FileWriter  save=new FileWriter(guarda+".txt");
           save.write(Salida.getText());
           save.close();
           JOptionPane.showMessageDialog(null,
                "El archivo se a guardado Exitosamente",
                    "Información",JOptionPane.INFORMATION_MESSAGE);
           }
        }
         catch(IOException ex)
         {
          JOptionPane.showMessageDialog(null,
               "Su archivo no se ha guardado",
                  "Advertencia",JOptionPane.WARNING_MESSAGE);
         }
    }//GEN-LAST:event_SaveActionPerformed

    private void CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarActionPerformed
        Entrada.setText(Salida.getText());
        Salida.setText("");
    }//GEN-LAST:event_CambiarActionPerformed

    private void CryptanalysisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CryptanalysisMouseClicked
        if (Entrada.getText().length()>10)
        {
            JOptionPane.showMessageDialog(null, new Sneaky().cryptanalysis(Entrada.getText())? 
                    "Fue cifrado por Transposicion":"Fue cifrado por Sustitucion", "Cryptanalysis",
                    JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese un texto con más de 10 caracteres", 
        "Cryptanalysis", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_CryptanalysisMouseClicked

    private void SherlockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SherlockMouseClicked
        if (Entrada.getText().length()>10)
        {
            if  (sherlock==null)
                sherlock=new Sherlock();
            sherlock.setFrecuencias(Entrada.getText());
            sherlock.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese un texto con más de 10 caracteres", 
        "Cryptanalysis", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SherlockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Abrir;
    private javax.swing.JButton Cambiar;
    private javax.swing.JButton Cifrar;
    private javax.swing.JSpinner Clave;
    private javax.swing.JMenu Cryptanalysis;
    private javax.swing.JButton Descifrar;
    private javax.swing.JTextArea Entrada;
    private javax.swing.JComboBox<String> Metodo;
    private javax.swing.JButton Refresh;
    private javax.swing.JTextArea Salida;
    private javax.swing.JButton Save;
    private javax.swing.JMenu Sherlock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
