/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SneakyCodeGUI;

import Tools.Bumblebee;
import java.awt.Color;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author The Worst One
 */
public class Sherlock extends javax.swing.JFrame {

    /**
     * Creates new form Sherlock
     */
    DefaultTableModel model;
    DefaultTableModel claves;
    
    public Sherlock() {
        initComponents();
        this.getContentPane().setBackground(new Color(0,204,204));
        setLocationRelativeTo(null);
        TextFrecuency.getTableHeader().setReorderingAllowed(false) ;
        ABCFrecuency.getTableHeader().setReorderingAllowed(false) ;
        KeyTable.getTableHeader().setReorderingAllowed(false) ;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ABCFrecuency = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextFrecuency = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Key = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        KeyTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sherlock");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(550, 475));
        setMinimumSize(new java.awt.Dimension(550, 475));
        setPreferredSize(new java.awt.Dimension(550, 475));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        ABCFrecuency.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ABCFrecuency.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        ABCFrecuency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"E", "13.65%"},
                {"A", "11.80%"},
                {"O", "9.19%"},
                {"S", "7.98%"},
                {"R", "6.70%"},
                {"N", "6.69%"},
                {"I", "6.89%"},
                {"L", "5.27%"},
                {"D", "5.19%"},
                {"C", "4.91%"}
            },
            new String [] {
                "Los más usados", "Frecuencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ABCFrecuency.setEnabled(false);
        jScrollPane1.setViewportView(ABCFrecuency);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 250, 190));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setOpaque(false);

        TextFrecuency.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TextFrecuency.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        TextFrecuency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Carácter en texto", "Frecuencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TextFrecuency);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, 190));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Frecuencias del Alfabeto Español");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 230, -1));

        Key.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        Key.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Key.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Key, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 200, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 520, 10));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 80, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setText("Frecuencias obtenidas del Cryptanalisis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setText("El programa obtuvo las siguientes claves: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 260, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setText("La clave tentativa es:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 140, -1));

        jScrollPane3.setOpaque(false);

        KeyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Crypt", "Original", "Clave"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(KeyTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 240, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 453));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setFrecuencias(String message){
        int size = message.length();
        Bumblebee bee = new Bumblebee();
        Key.setText(String.valueOf(bee.honeyPot3(message)));
        Map<String,Integer> frecuency = bee.getFrecuency();
        Map<String,Integer> sherlock = bee.getSherlock();
        int i = 0;
        Object [][] row = new Object[frecuency.size()][2];
        String [] modelHeader = {"Carácter en texto","Frecuencia"};
        String [] clavesHeader = {"Crypt","Original","Clave"};
        Iterator<String> it = frecuency.keySet().iterator();
        while(it.hasNext()){
            String clave = it.next();
            row[i][0]=clave; row[i][1]=String.format("%.2f %s",((double)frecuency.get(clave)/(double)size)*100,"%");
            //model.addRow(row); 
            i++;
        }
        
        i = 0;
        Object [][] keys = new Object[sherlock.size()][3];
        it = sherlock.keySet().iterator();
        while(it.hasNext()){
            String clave = it.next();
            keys[i][0] = clave; keys[i][1]= "A"; keys[i][2]= bee.location("A", clave);
            //claves.addRow(keys);
            i++;
        }
        
        model = new DefaultTableModel(row, modelHeader){@Override
                                        public boolean isCellEditable(int row, int column) {
                                            return false;} };
        claves = new DefaultTableModel(keys,clavesHeader){@Override
                                        public boolean isCellEditable(int row, int column) {
                                            return false;} };
        TextFrecuency.setModel(model);
        KeyTable.setModel(claves);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sherlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sherlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sherlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sherlock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sherlock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ABCFrecuency;
    private javax.swing.JLabel Key;
    private javax.swing.JTable KeyTable;
    private javax.swing.JTable TextFrecuency;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
